# Generated by Django 6.0.4 on 2026-07-29 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messagerie', '0001_initial'),
        ('Registration', '0015_profil_categories_produits'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('reponse', models.TextField(blank=True, default='')),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('admin_repondant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_admin_repondus', to='Registration.utilisateur')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_admin_envoyes', to='Registration.utilisateur')),
            ],
            options={
                'verbose_name': 'message admin',
                'verbose_name_plural': 'messages admin',
                'db_table': 'messages_admin',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
