# Generated by Django 6.0.4 on 2026-08-01 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messagerie', '0002_messagesupport'),
        ('Registration', '0018_utilisateur_desactive_par_signalements'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalementMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_probleme', models.CharField(choices=[('contenu_inapproprie', 'Contenu inapproprié'), ('harcelement', 'Harcèlement / menaces'), ('spam', 'Spam / publicité'), ('arnaque_fraude', 'Arnaque / fraude'), ('autre', 'Autre')], max_length=30)),
                ('motif', models.TextField()),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('admin_traitant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_messages_traites', to='Registration.utilisateur')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='Messagerie.message')),
                ('signaleur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_messages_effectues', to='Registration.utilisateur')),
            ],
            options={
                'verbose_name': 'signalement message',
                'verbose_name_plural': 'signalements messages',
                'db_table': 'signalements_messages',
                'ordering': ['-date_signalement'],
            },
        ),
    ]
