# Generated by Django 6.0.4 on 2026-08-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messagerie', '0003_signalementmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chiffre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='iv',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='messagesupport',
            name='chiffre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messagesupport',
            name='cles_contenu',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagesupport',
            name='cles_reponse',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagesupport',
            name='iv_contenu',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='messagesupport',
            name='iv_reponse',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='signalementmessage',
            name='contenu_signale',
            field=models.TextField(blank=True),
        ),
    ]
