# Generated by Django 6.0.4 on 2026-08-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messagerie', '0004_message_chiffre_message_iv_messagesupport_chiffre_and_more'),
        ('Registration', '0021_remove_clechiffrementutilisateur_cle_privee_chiffree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='supprime_pour',
            field=models.ManyToManyField(blank=True, related_name='conversations_supprimees', to='Registration.utilisateur'),
        ),
        migrations.AddField(
            model_name='message',
            name='supprime_pour',
            field=models.ManyToManyField(blank=True, related_name='messages_supprimes', to='Registration.utilisateur'),
        ),
    ]
