# Generated by Django 6.0.4 on 2026-08-06 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messagerie', '0005_conversation_supprime_pour_message_supprime_pour'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='repond_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reponses', to='Messagerie.message'),
        ),
    ]
