# Generated by Django 6.0.4 on 2026-08-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Messagerie", "0006_message_repond_a"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagesupport",
            name="format_chiffrement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("e2e_client", "Chiffré de bout en bout (client, legacy)"),
                    ("coffre_serveur", "Chiffré côté serveur (coffre support)"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="messagesupport",
            name="reponse_format_chiffrement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("e2e_client", "Chiffré de bout en bout (client, legacy)"),
                    ("coffre_serveur", "Chiffré côté serveur (coffre support)"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
