# Generated by Django 6.0.4 on 2026-08-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Messagerie", "0008_backfill_format_chiffrement_legacy"),
        ("Registration", "0027_backfill_super_super_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagesupport",
            name="historique_masque_pour",
            field=models.ManyToManyField(
                blank=True,
                related_name="messages_support_historique_masques",
                to="Registration.utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="signalementmessage",
            name="historique_masque_pour",
            field=models.ManyToManyField(
                blank=True,
                related_name="signalements_messages_historique_masques",
                to="Registration.utilisateur",
            ),
        ),
    ]
