# Generated by Django 6.0.4 on 2026-08-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Messagerie", "0009_messagesupport_historique_masque_pour_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="signalementmessage",
            name="explication_decision",
            field=models.TextField(blank=True, default=""),
        ),
    ]
