"""
Réglages COMMUNS aux deux environnements (développement et production).

Ce module n'est jamais utilisé seul comme DJANGO_SETTINGS_MODULE : il est
importé par settings/dev.py ou settings/prod.py, qui y ajoutent/surchargent
les réglages propres à leur environnement (DEBUG, DATABASES, ALLOWED_HOSTS,
stockage des fichiers médias, ...).

Important : dev.py et prod.py chargent le fichier .env correspondant AVANT
d'importer ce module (`from .base import *`), afin que les os.getenv()
ci-dessous lisent déjà les bonnes valeurs.

Generated by 'django-admin startproject' using Django 6.0.4, puis scindé en
package settings/ pour éviter de dupliquer la config entre dev et prod.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BackendRekoltHt/settings/base.py -> remonter de 3 niveaux pour la racine du projet
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')


# Application definition

INSTALLED_APPS = [
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',    'rest_framework',
    'corsheaders',
    'Api',
    'RekoltHt',
    'Produits',
    'Registration',
    'Messagerie',
    'Sauvegarde',
    'social_django',
]
# ne pas toucher
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    # convertit un ValueError/TypeError non intercepté (ex: id non numérique
    # dans une query string) en réponse JSON 400 propre plutôt qu'une 500
    # générique — voir Api/middleware.py pour le constat détaillé (audit de
    # sécurité, pas une injection SQL : l'ORM refuse déjà la conversion)
    "Api.middleware.ExceptionJsonMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# configuration WhiteNoise
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
STATIC_URL          = '/static/'
STATIC_ROOT         = os.path.join(BASE_DIR, 'staticfiles')

# autoriser la communication entre react et django
CORS_ALLOWED_ORIGINS = ["http://localhost:5173","https://rekolthtfront.onrender.com","http://192.168.1.4:5173"]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    "GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"
]
# autorisere les entete dans les requete
CORS_ALLOW_HEADERS = [
    "accept",
    "authorization",
    "content-type",
    "origin",
    "x-csrftoken",
    "x-requested-with",
]
# autorise les requete post avec CSRF
CSRF_TRUSTED_ORIGINS = ["http://localhost:5173","https://rekolthtfront.onrender.com/","http://192.168.1.4:5173"]

# ASGI ET WebSocket
ASGI_APPLICATION = 'BackendRekoltHt.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer'
    }
}
# DRF et authentification API
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": ["rest_framework.authentication.TokenAuthentication"],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
}
ROOT_URLCONF = 'BackendRekoltHt.urls'

# Google OAuth
AUTHENTICATION_BACKENDS = [
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
]
SECURE_CROSS_ORIGIN_OPENER_POLICY = None

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY    = os.getenv('SOCIAL_AUTH_GOOGLE_OAUTH2_KEY')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.getenv('SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET')

SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    'openid',
    'email',
    'profile',
]


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'BackendRekoltHt.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Fuseau horaire d'Haïti (UTC-5, EST — Haïti observe aussi l'heure d'été,
# 'America/Port-au-Prince' gère cette règle automatiquement contrairement à un
# simple décalage fixe) : la plateforme n'a d'utilisateurs qu'en Haïti, tous
# les horodatages affichés (timezone.localtime/localdate — rapports PDF,
# dates "aujourd'hui" des sélecteurs de période, etc.) doivent refléter
# l'heure locale d'Haïti, pas UTC. Les données restent stockées en UTC en
# base (USE_TZ=True ci-dessous) — seul l'AFFICHAGE change.
TIME_ZONE = 'America/Port-au-Prince'

USE_I18N = True

USE_TZ = True


# Fichiers médias (photos de profil, logos, etc.)
# MEDIA_URL est commun ; MEDIA_ROOT (stockage local) et le stockage externe de
# production sont définis dans dev.py / prod.py — voir les points critiques
# documentés dans prod.py avant tout déploiement.
MEDIA_URL = '/media/'

# les photos/logos sont envoyées en base64 dans le JSON (~+33% de taille) — la limite
# par défaut de Django (~2.6 Mo) est donc trop basse pour les images de 5 Mo annoncées au frontend
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 Mo

# ── CONFIGURATION EMAIL ───────────────────────────────────────────────────────
EMAIL_BACKEND       = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST          = os.getenv('EMAIL_HOST')
EMAIL_PORT          = int(os.getenv('EMAIL_PORT'))
EMAIL_USE_TLS       = os.getenv('EMAIL_USE_TLS') == 'True'
EMAIL_HOST_USER     = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL  = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# ── reCAPTCHA ──────────────────────────────────────────────────────────────────
# clé secrète de vérification côté serveur (voir Registration/views.py::
# _verifier_recaptcha, utilisée par creerAdmin) — distincte de la clé de site
# publique VITE_RECAPTCHA_KEY côté frontend. Si absente, la vérification est
# ignorée (dev sans clé) plutôt que de bloquer toute création de compte admin.
RECAPTCHA_SECRET_KEY = os.getenv('RECAPTCHA_SECRET_KEY')


# ── SAUVEGARDES (voir Sauvegarde/) ────────────────────────────────────────────
# clé maître de chiffrement des fichiers .rhtbackup (Fernet, voir
# Sauvegarde/services/chiffrement_service.py) — dédiée, indépendante de
# SECRET_KEY et de tout mot de passe utilisateur, pour qu'un backup reste
# restaurable même si les comptes admin changent. Générée une fois via
# Fernet.generate_key() et collée dans .env/.env.dev, jamais en base.
BACKUP_MASTER_KEY = os.getenv('BACKUP_MASTER_KEY')

# ── MESSAGERIE SUPPORT (voir Messagerie/) ─────────────────────────────────────
# clé maître de chiffrement des messages "vendeur/acheteur -> administrateurs"
# (Fernet, voir Messagerie/services/support_chiffrement_service.py). Choix
# assumé (demandé explicitement par le propriétaire) : contrairement à la
# messagerie privée 1:1 (chiffrement de bout en bout, jamais lisible par le
# serveur), les messages support sont chiffrés UNIQUEMENT contre un accès
# base de données brut — le serveur applicatif, lui, peut toujours les
# déchiffrer. Contrepartie acceptée en échange d'un vrai bénéfice : un admin
# auquel le droit gestion_support est accordé APRÈS l'envoi d'un message peut
# quand même le lire et y répondre immédiatement, sans dépendre d'un autre
# admin encore en ligne pour "réparer" une enveloppe de clé E2E manquante
# (impossible par nature avec le chiffrement de bout en bout — voir l'ancien
# schéma, toujours conservé en lecture seule pour les messages antérieurs à
# ce changement, voir MessageSupport.format_chiffrement).
SUPPORT_MASTER_KEY = os.getenv('SUPPORT_MASTER_KEY')

# ── MESSAGERIE PRIVÉE 1:1 (voir Messagerie/) ──────────────────────────────────
# clé maître de chiffrement des messages privés entre deux utilisateurs
# (Fernet, voir Messagerie/services/messages_chiffrement_service.py). Jusqu'ici
# cette messagerie était chiffrée de BOUT EN BOUT (clé gérée par le
# navigateur de chaque utilisateur, jamais lisible par le serveur) — décision
# explicitement inversée par le propriétaire : demande que les messages
# restent accessibles immédiatement sur n'importe quel appareil/navigateur dès
# la connexion, sans jamais redemander de mot de passe ni de clé côté client.
# Même compromis, déjà en place pour la messagerie support (voir
# SUPPORT_MASTER_KEY ci-dessus) : chiffré contre un accès base de données brut,
# mais le serveur applicatif peut toujours le déchiffrer pour un participant
# authentifié de la conversation.
MESSAGES_MASTER_KEY = os.getenv('MESSAGES_MASTER_KEY')

# dossier de stockage des sauvegardes "locales" — même avertissement que
# MEDIA_ROOT ci-dessous : sur un hébergeur au système de fichiers éphémère
# (ex. Render), ce dossier ne survit pas à un redéploiement ; la destination
# "locale" n'est fiable qu'en auto-hébergement ou en développement, sinon
# préférer la destination "google_drive"
SAUVEGARDE_ROOT = BASE_DIR / 'sauvegardes'

# identifiants OAuth2 dédiés à l'upload Google Drive (scope drive.file
# uniquement — l'app ne voit que les fichiers qu'elle crée elle-même), voir
# Sauvegarde/services/google_drive_service.py. Distincts de
# SOCIAL_AUTH_GOOGLE_OAUTH2_KEY/SECRET (connexion des utilisateurs) même s'ils
# peuvent techniquement provenir du même projet Google Cloud.
GOOGLE_DRIVE_CLIENT_ID     = os.getenv('GOOGLE_DRIVE_CLIENT_ID')
GOOGLE_DRIVE_CLIENT_SECRET = os.getenv('GOOGLE_DRIVE_CLIENT_SECRET')
GOOGLE_DRIVE_REDIRECT_URI  = os.getenv('GOOGLE_DRIVE_REDIRECT_URI')
# URL du frontend vers laquelle rediriger une fois le consentement Google
# Drive terminé (voir Sauvegarde/views.py::google_callback)
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')


# ── ASSISTANT IA DU CHATBOT (voir Messagerie/services/chatbot_ia_service.py) ──
# clé API OpenRouter (passerelle unique vers de nombreux modèles — GPT, Claude,
# etc., voir CHATBOT_IA_MODEL ci-dessous) — obtenue sur https://openrouter.ai.
# Laisser vide désactive l'assistant IA : ChatbotVendeur.jsx dégrade alors
# proprement vers la proposition de contacter un administrateur (même
# convention que RECAPTCHA_SECRET_KEY/FACE_VENV_PYTHON ci-dessus/ci-dessous —
# une clé optionnelle absente désactive la fonctionnalité, ne casse rien).
OPENROUTER_API_KEY = os.getenv('OPENROUTER_API_KEY')
# modèle utilisé, au format OpenRouter "fournisseur/modele" (ex. "openai/gpt-4o",
# "openai/gpt-4o-mini", "anthropic/claude-haiku-4.5"...) — changeable sans
# redéploiement de code, voir https://openrouter.ai/models pour la liste et les
# tarifs de chacun
CHATBOT_IA_MODEL = os.getenv('CHATBOT_IA_MODEL', 'openai/gpt-4o')


# ── VÉRIFICATION FACIALE (DeepFace, environnement Python dédié) ──────────────
# DeepFace (via TensorFlow) exige protobuf>=6.31.1, incompatible avec
# paddleocr/paddlepaddle (protobuf<=3.20.2, voir requirements.txt) dans le même
# environnement — vérifié : `import paddle` échoue dès que deepface est
# installé à côté. FACE_VENV_PYTHON pointe donc vers le python d'un second
# environnement dédié (voir requirements-face.txt), invoqué via subprocess par
# Registration/services/face_service.py — jamais importé dans ce processus.
FACE_VENV_PYTHON = os.getenv('FACE_VENV_PYTHON')
