"""
Réglages COMMUNS aux deux environnements (développement et production).

Ce module n'est jamais utilisé seul comme DJANGO_SETTINGS_MODULE : il est
importé par settings/dev.py ou settings/prod.py, qui y ajoutent/surchargent
les réglages propres à leur environnement (DEBUG, DATABASES, ALLOWED_HOSTS,
stockage des fichiers médias, ...).

Important : dev.py et prod.py chargent le fichier .env correspondant AVANT
d'importer ce module (`from .base import *`), afin que les os.getenv()
ci-dessous lisent déjà les bonnes valeurs.

Generated by 'django-admin startproject' using Django 6.0.4, puis scindé en
package settings/ pour éviter de dupliquer la config entre dev et prod.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BackendRekoltHt/settings/base.py -> remonter de 3 niveaux pour la racine du projet
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-(oo&i=gt9nv@!dux%%568cbpm3@hi==w3%z)%uhg(q!w@kj&hb')


# Application definition

INSTALLED_APPS = [
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'Api',
    'RekoltHt',
    'Produits',
    'Registration',
    'social_django',
]
# ne pas toucher
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# configuration WhiteNoise
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
STATIC_URL          = '/static/'
STATIC_ROOT         = os.path.join(BASE_DIR, 'staticfiles')

# autoriser la communication entre react et django
CORS_ALLOWED_ORIGINS = ["http://localhost:5173","https://rekolthtfront.onrender.com"]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    "GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"
]
# autorisere les entete dans les requete
CORS_ALLOW_HEADERS = [
    "accept",
    "authorization",
    "content-type",
    "origin",
    "x-csrftoken",
    "x-requested-with",
]
# autorise les requete post avec CSRF
CSRF_TRUSTED_ORIGINS = ["http://localhost:5173","https://rekolthtfront.onrender.com/"]

# ASGI ET WebSocket
ASGI_APPLICATION = 'BackendRekoltHt.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer'
    }
}
# DRF et authentification API
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": ["rest_framework.authentication.TokenAuthentication"],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
}
ROOT_URLCONF = 'BackendRekoltHt.urls'

# Google OAuth
AUTHENTICATION_BACKENDS = [
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
]
SECURE_CROSS_ORIGIN_OPENER_POLICY = None

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY    = os.getenv('SOCIAL_AUTH_GOOGLE_OAUTH2_KEY')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.getenv('SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET')

SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    'openid',
    'email',
    'profile',
]


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'BackendRekoltHt.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Fichiers médias (photos de profil, logos, etc.)
# MEDIA_URL est commun ; MEDIA_ROOT (stockage local) et le stockage externe de
# production sont définis dans dev.py / prod.py — voir les points critiques
# documentés dans prod.py avant tout déploiement.
MEDIA_URL = '/media/'

# les photos/logos sont envoyées en base64 dans le JSON (~+33% de taille) — la limite
# par défaut de Django (~2.6 Mo) est donc trop basse pour les images de 5 Mo annoncées au frontend
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 Mo

# ── CONFIGURATION EMAIL ───────────────────────────────────────────────────────
EMAIL_BACKEND       = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST          = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT          = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS       = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER     = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL  = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)


# ── VÉRIFICATION FACIALE (DeepFace, environnement Python dédié) ──────────────
# DeepFace (via TensorFlow) exige protobuf>=6.31.1, incompatible avec
# paddleocr/paddlepaddle (protobuf<=3.20.2, voir requirements.txt) dans le même
# environnement — vérifié : `import paddle` échoue dès que deepface est
# installé à côté. FACE_VENV_PYTHON pointe donc vers le python d'un second
# environnement dédié (voir requirements-face.txt), invoqué via subprocess par
# Registration/services/face_service.py — jamais importé dans ce processus.
FACE_VENV_PYTHON = os.getenv('FACE_VENV_PYTHON')
