# Generated by Django 6.0.4 on 2026-06-25 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_Entreprise', models.CharField(max_length=100)),
                ('num_Enregistrement', models.CharField(max_length=100, unique=True)),
                ('secteur', models.CharField(choices=[('agriculture', 'Agriculture'), ('transformation', 'Transformation'), ('distribution', 'Distribution'), ('autre', 'Autre')], default='agriculture', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('commune', models.CharField(blank=True, max_length=100)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('pays', models.CharField(default='Haiti', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_entreprise/')),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('est_verifiee', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entreprises', to='Registration.utilisateur')),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'db_table': 'entreprise',
                'ordering': ['id'],
            },
        ),
    ]
