# Generated by Django 6.0.4 on 2026-06-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='nom_entreprise',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='piece_justificative',
            field=models.FileField(blank=True, null=True, upload_to='pieces_justificatives/'),
        ),
        migrations.AddField(
            model_name='profil',
            name='statut_verification',
            field=models.CharField(choices=[('non_requis', 'Non requis'), ('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='non_requis', max_length=20),
        ),
        migrations.AddField(
            model_name='profil',
            name='type_vendeur',
            field=models.CharField(blank=True, choices=[('individu', 'Individu'), ('entreprise', 'Entreprise')], max_length=20, null=True),
        ),
    ]
