# Generated by Django 6.0.4 on 2026-06-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='est_bloquer',
            field=models.BooleanField(default=False),
        ),
    ]
