# Generated by Django 6.0.4 on 2026-06-20 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_profil_nom_entreprise_profil_piece_justificative_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='nom_entreprise',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='piece_justificative',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='statut_verification',
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_entreprise', models.CharField(blank=True, max_length=150, null=True)),
                ('piece_justificative', models.FileField(blank=True, null=True, upload_to='pieces_justificatives/')),
                ('statut_verification', models.CharField(choices=[('non_requis', 'Non requis'), ('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='non_requis', max_length=20)),
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entreprise', to='Registration.profil')),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'db_table': 'entreprise',
            },
        ),
    ]
