# Generated by Django 6.0.4 on 2026-06-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_remove_profil_nom_entreprise_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entreprise',
            options={'ordering': ['id'], 'verbose_name': 'Entreprise', 'verbose_name_plural': 'Entreprises'},
        ),
        migrations.AddField(
            model_name='entreprise',
            name='date_maj',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='nom_entreprise',
            field=models.CharField(default='exit', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='statut_verification',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20),
        ),
    ]
