# Generated by Django 6.0.4 on 2026-06-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_utilisateur_est_bloquer'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='statut_verification',
            field=models.CharField(choices=[('en attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en attente', max_length=20),
        ),
    ]
