# Generated by Django 6.0.4 on 2026-06-26 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0004_entreprise_statut_verification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprise',
            name='ville',
        ),
    ]
