# Generated by Django 6.0.4 on 2026-06-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0005_remove_entreprise_ville'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='nom_Entreprise',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
