# Generated by Django 6.0.4 on 2026-06-30 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0006_alter_entreprise_nom_entreprise'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeReinitialisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField()),
                ('utilise', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_reinitialisation', to='Registration.utilisateur')),
            ],
            options={
                'verbose_name': 'Code de réinitialisation',
                'verbose_name_plural': 'Codes de réinitialisation',
                'db_table': 'code_reinitialisation',
                'ordering': ['-date_creation'],
            },
        ),
    ]
