# Generated by Django 6.0.4 on 2026-07-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0009_heritage_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='role',
            field=models.CharField(choices=[('acheteur', 'Acheteur'), ('vendeur', 'Vendeur'), ('admin', 'Admin')], default='acheteur', max_length=20),
        ),
    ]
