# Generated by Django 6.0.4 on 2026-07-06 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0010_alter_profil_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='proprietaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entreprises', to='Registration.utilisateur'),
        ),
    ]
