# Generated by Django 6.0.4 on 2026-07-10 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Registration", "0011_alter_entreprise_proprietaire"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandeVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_demandeur",
                    models.CharField(
                        choices=[
                            ("individuel", "Individuel"),
                            ("entreprise", "Entreprise"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "type_document",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("passeport", "Passeport"),
                            ("permis", "Permis de conduire"),
                            ("cin", "Carte d'identité"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "document_recto",
                    models.ImageField(
                        blank=True, null=True, upload_to="verification/documents/"
                    ),
                ),
                (
                    "document_verso",
                    models.ImageField(
                        blank=True, null=True, upload_to="verification/documents/"
                    ),
                ),
                (
                    "selfie",
                    models.ImageField(
                        blank=True, null=True, upload_to="verification/selfies/"
                    ),
                ),
                (
                    "certificat_patente",
                    models.FileField(
                        blank=True, null=True, upload_to="verification/patentes/"
                    ),
                ),
                (
                    "numero_patente_extrait",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "nom_extrait",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "prenom_extrait",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "numero_piece_extrait",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_naissance_extraite", models.DateField(blank=True, null=True)),
                ("donnees_ocr_brutes", models.JSONField(blank=True, null=True)),
                (
                    "score_correspondance_visage",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("verifie", "Vérifié"),
                            ("echoue", "Échoué"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("motif_echec", models.TextField(blank=True, null=True)),
                (
                    "contrat_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="verification/contrats/"
                    ),
                ),
                ("date_soumission", models.DateTimeField(auto_now_add=True)),
                ("date_traitement", models.DateTimeField(blank=True, null=True)),
                (
                    "utilisateur",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demande_verification",
                        to="Registration.utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de vérification",
                "verbose_name_plural": "Demandes de vérification",
                "db_table": "demande_verification",
                "ordering": ["-date_soumission"],
            },
        ),
    ]
