# Generated by Django 6.0.4 on 2026-07-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Registration", "0012_demandeverification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demandeverification",
            name="statut",
            field=models.CharField(
                choices=[
                    ("en_attente", "En attente"),
                    ("en_attente_manuelle", "En attente de revue manuelle"),
                    ("verifie", "Vérifié"),
                    ("echoue", "Échoué"),
                ],
                default="en_attente",
                max_length=20,
            ),
        ),
    ]
