# Generated by Django 6.0.4 on 2026-07-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Registration", "0013_alter_demandeverification_statut"),
    ]

    operations = [
        migrations.AddField(
            model_name="demandeverification",
            name="numero_piece_saisi",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
