# Generated by Django 6.0.4 on 2026-07-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0001_initial'),
        ('Registration', '0014_demandeverification_numero_piece_saisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='categories_produits',
            field=models.ManyToManyField(blank=True, related_name='vendeurs', to='Produits.categories'),
        ),
    ]
