# Generated by Django 6.0.4 on 2026-08-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0015_profil_categories_produits'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='departement',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='section_communale',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profil',
            name='departement',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profil',
            name='section_communale',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
