# Generated by Django 6.0.4 on 2026-08-01 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0016_entreprise_departement_entreprise_section_communale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprise',
            name='num_Enregistrement',
        ),
    ]
