# Generated by Django 6.0.4 on 2026-08-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0017_remove_entreprise_num_enregistrement'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='desactive_par_signalements',
            field=models.BooleanField(default=False),
        ),
    ]
