# Generated by Django 6.0.4 on 2026-08-02 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0018_utilisateur_desactive_par_signalements'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='nombre_vues_profil',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
