# Generated by Django 6.0.4 on 2026-08-02 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0019_utilisateur_nombre_vues_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleChiffrementUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle_publique', models.TextField()),
                ('cle_privee_chiffree', models.TextField()),
                ('iv_cle_privee', models.CharField(max_length=64)),
                ('sel_kdf', models.CharField(max_length=64)),
                ('iterations_kdf', models.PositiveIntegerField(default=210000)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cle_chiffrement', to='Registration.utilisateur')),
            ],
            options={
                'verbose_name': 'Clé de chiffrement',
                'verbose_name_plural': 'Clés de chiffrement',
                'db_table': 'cle_chiffrement_utilisateur',
            },
        ),
    ]
