# Generated by Django 6.0.4 on 2026-08-06 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0020_clechiffrementutilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clechiffrementutilisateur',
            name='cle_privee_chiffree',
        ),
        migrations.RemoveField(
            model_name='clechiffrementutilisateur',
            name='iterations_kdf',
        ),
        migrations.RemoveField(
            model_name='clechiffrementutilisateur',
            name='iv_cle_privee',
        ),
        migrations.RemoveField(
            model_name='clechiffrementutilisateur',
            name='sel_kdf',
        ),
    ]
