# Generated by Django 6.0.4 on 2026-08-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0021_remove_clechiffrementutilisateur_cle_privee_chiffree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clechiffrementutilisateur',
            name='cle_privee_chiffree',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clechiffrementutilisateur',
            name='iterations_kdf',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clechiffrementutilisateur',
            name='iv_cle_privee',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='clechiffrementutilisateur',
            name='sel_kdf',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
