# Generated by Django 6.0.4 on 2026-08-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0022_clechiffrementutilisateur_cle_privee_chiffree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='nombre_avertissements',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
