# Generated by Django 6.0.4 on 2026-08-06 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0023_utilisateur_nombre_avertissements'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroitsAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('super_admin', models.BooleanField(default=False)),
                ('gestion_utilisateurs', models.BooleanField(default=False)),
                ('gestion_signalements', models.BooleanField(default=False)),
                ('gestion_verifications', models.BooleanField(default=False)),
                ('gestion_categories', models.BooleanField(default=False)),
                ('gestion_support', models.BooleanField(default=False)),
                ('gestion_sauvegardes', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('attribue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='droits_attribues', to='Registration.utilisateur')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='droits_admin', to='Registration.utilisateur')),
            ],
            options={
                'verbose_name': 'Droits admin',
                'verbose_name_plural': 'Droits admin',
                'db_table': 'droits_admin',
            },
        ),
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_admin_snapshot', models.CharField(max_length=200)),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_audit', to='Registration.utilisateur')),
            ],
            options={
                'verbose_name': "Entrée d'audit",
                'verbose_name_plural': "Journal d'audit",
                'db_table': 'journal_audit',
                'ordering': ['-date_action'],
                'indexes': [models.Index(fields=['date_action', 'admin'], name='journal_aud_date_ac_f93e70_idx')],
            },
        ),
    ]
