# Generated by Django 6.0.4 on 2026-08-06 09:33
#
# Donne super_admin=True à tout compte déjà admin (Profil.role == 'admin')
# qui n'a pas encore de DroitsAdmin — sans ça, l'introduction du système de
# droits granulaires (voir DroitsAdmin, Registration/models.py) couperait
# instantanément l'accès de tous les admins existants au déploiement, aucun
# n'ayant de droit tant qu'on ne leur en attribue pas explicitement.

from django.db import migrations


def backfill_super_admin(apps, schema_editor):
    Profil = apps.get_model('Registration', 'Profil')
    DroitsAdmin = apps.get_model('Registration', 'DroitsAdmin')

    admins_sans_droits = Profil.objects.filter(role='admin').exclude(
        utilisateur__droits_admin__isnull=False
    )
    for profil in admins_sans_droits:
        DroitsAdmin.objects.create(utilisateur=profil.utilisateur, super_admin=True)


def revenir_en_arriere(apps, schema_editor):
    # rien à défaire : supprimer les DroitsAdmin créés par cette migration
    # supprimerait aussi ceux créés manuellement depuis — pas réversible
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0024_droitsadmin_journalaudit'),
    ]

    operations = [
        migrations.RunPython(backfill_super_admin, revenir_en_arriere),
    ]
