# Generated by Django 6.0.4 on 2026-08-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0025_backfill_super_admin_existants'),
    ]

    operations = [
        migrations.AddField(
            model_name='droitsadmin',
            name='est_super_super_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='droitsadmin',
            name='gestion_mots_de_passe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='doit_changer_mot_de_passe',
            field=models.BooleanField(default=False),
        ),
    ]
