# Generated by Django 6.0.4 on 2026-08-09 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Registration", "0027_backfill_super_super_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="VueProfilVendeur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_vue", models.DateTimeField(auto_now_add=True)),
                (
                    "vendeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vues_profil",
                        to="Registration.utilisateur",
                    ),
                ),
                (
                    "visiteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vues_profils_effectuees",
                        to="Registration.utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "vue profil vendeur",
                "verbose_name_plural": "vues profils vendeurs",
                "db_table": "vues_profil_vendeur",
                "ordering": ["-date_vue"],
            },
        ),
    ]
