# Generated by Django 6.0.4 on 2026-08-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Registration", "0028_vueprofilvendeur"),
    ]

    operations = [
        migrations.CreateModel(
            name="InscriptionEnAttente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("mot_de_passe", models.CharField(max_length=255)),
                ("telephone", models.CharField(max_length=20)),
                ("donnees_optionnelles", models.JSONField(blank=True, default=dict)),
                ("token", models.CharField(max_length=64, unique=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_expiration", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Inscription en attente d'activation",
                "verbose_name_plural": "Inscriptions en attente d'activation",
                "db_table": "inscription_en_attente",
                "ordering": ["-date_creation"],
            },
        ),
    ]
