# Generated by Django 6.0.4 on 2026-08-09 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Registration", "0029_inscriptionenattente"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandeAdministrative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("objet", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("approuvee", "Approuvée"),
                            ("rejetee", "Rejetée"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("reponse_admin", models.TextField(blank=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_traitement", models.DateTimeField(blank=True, null=True)),
                (
                    "admin_traitant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="demandes_administratives_traitees",
                        to="Registration.utilisateur",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demandes_administratives",
                        to="Registration.utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "demande administrative",
                "verbose_name_plural": "demandes administratives",
                "db_table": "demandes_administratives",
                "ordering": ["-date_creation"],
            },
        ),
    ]
