# Generated by Django 6.0.4 on 2026-08-10 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Registration", "0030_demandeadministrative"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="raison_blocage",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="CompteSupprime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("raison", models.TextField()),
                ("date_suppression", models.DateTimeField(auto_now_add=True)),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comptes_supprimes",
                        to="Registration.utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "compte supprimé",
                "verbose_name_plural": "comptes supprimés",
                "db_table": "comptes_supprimes",
                "ordering": ["-date_suppression"],
            },
        ),
    ]
