# Generated by Django 6.0.4 on 2026-08-10 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Registration", "0031_utilisateur_raison_blocage_comptesupprime"),
    ]

    operations = [
        migrations.AddField(
            model_name="demandeadministrative",
            name="email_contact",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="demandeadministrative",
            name="nom_contact",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="demandeadministrative",
            name="utilisateur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="demandes_administratives",
                to="Registration.utilisateur",
            ),
        ),
    ]
