# Generated by Django 6.0.4 on 2026-08-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0032_demandeadministrative_email_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeverification',
            name='motif_revue_manuelle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
