# Generated by Django 6.0.4 on 2026-08-27 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Registration", "0033_demandeverification_motif_revue_manuelle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="demandeverification",
            name="document_verso",
        ),
    ]
