# Generated by Django 6.0.4 on 2026-08-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Registration", "0034_remove_demandeverification_document_verso"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscriptionenattente",
            name="type_compte",
            field=models.CharField(
                choices=[("individuel", "Individuel"), ("entreprise", "Entreprise")],
                default="individuel",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="inscriptionenattente",
            name="prenom",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
