# Generated by Django 6.0.4 on 2026-08-06 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Registration', '0025_backfill_super_admin_existants'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationSauvegarde',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('frequence', models.CharField(choices=[('quotidienne', 'Quotidienne'), ('hebdomadaire', 'Hebdomadaire'), ('mensuelle', 'Mensuelle')], default='quotidienne', max_length=20)),
                ('heure_declenchement', models.TimeField(default='02:00')),
                ('jour_semaine', models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], default=0)),
                ('jour_mois', models.PositiveSmallIntegerField(default=1)),
                ('type_sauvegarde', models.CharField(choices=[('complete', 'Complète'), ('incrementale', 'Incrémentale')], default='complete', max_length=20)),
                ('destination', models.CharField(choices=[('locale', 'Locale (serveur)'), ('google_drive', 'Google Drive')], default='locale', max_length=20)),
                ('google_drive_connecte', models.BooleanField(default=False)),
                ('google_drive_refresh_token_chiffre', models.TextField(blank=True, null=True)),
                ('google_drive_dossier_id', models.CharField(blank=True, max_length=255, null=True)),
                ('derniere_execution_reussie', models.DateTimeField(blank=True, null=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configurations_sauvegarde_modifiees', to='Registration.utilisateur')),
            ],
            options={
                'verbose_name': 'Configuration de sauvegarde',
                'verbose_name_plural': 'Configuration de sauvegarde',
                'db_table': 'configuration_sauvegarde',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueSauvegarde',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_execution', models.DateTimeField(auto_now_add=True)),
                ('type_sauvegarde', models.CharField(choices=[('complete', 'Complète'), ('incrementale', 'Incrémentale')], max_length=20)),
                ('destination', models.CharField(choices=[('locale', 'Locale (serveur)'), ('google_drive', 'Google Drive')], max_length=20)),
                ('statut', models.CharField(choices=[('succes', 'Succès'), ('echec', 'Échec')], max_length=10)),
                ('message_erreur', models.TextField(blank=True, null=True)),
                ('taille_octets', models.BigIntegerField(blank=True, null=True)),
                ('nombre_enregistrements', models.IntegerField(blank=True, null=True)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('chemin_fichier_local', models.CharField(blank=True, max_length=500, null=True)),
                ('google_drive_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('est_sauvegarde_securite', models.BooleanField(default=False)),
                ('declenche_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sauvegardes_declenchees', to='Registration.utilisateur')),
            ],
            options={
                'verbose_name': 'Historique de sauvegarde',
                'verbose_name_plural': 'Historique des sauvegardes',
                'db_table': 'historique_sauvegarde',
                'ordering': ['-date_execution'],
            },
        ),
    ]
