# Generated by Django 6.0.4 on 2026-09-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sauvegarde", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="configurationsauvegarde",
            name="verification_planifiee_en_cours_depuis",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
