# Generated by Django 6.0.4 on 2026-07-21 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Registration', '0014_demandeverification_numero_piece_saisi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'categories',
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix', models.FloatField(blank=True, null=True)),
                ('unite', models.CharField(blank=True, max_length=100)),
                ('est_disponible', models.BooleanField(default=False)),
                ('departement', models.CharField(blank=True, max_length=100)),
                ('commune', models.CharField(blank=True, max_length=100)),
                ('section_comunale', models.CharField(blank=True, max_length=100)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='Produits.categories')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs', to='Registration.utilisateur', verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'produits',
                'verbose_name_plural': 'produits',
                'db_table': 'produits',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='photo_produits',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url_photo', models.ImageField(blank=True, null=True, upload_to='photos_produits/')),
                ('produits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='Produits.produits')),
            ],
        ),
    ]
