# Generated by Django 6.0.4 on 2026-07-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produits',
            name='date_maj',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='produits',
            name='photo',
            field=models.ImageField(default='', upload_to='photos_produits/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produits',
            name='quantite',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produits',
            name='region',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produits',
            name='statut',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('indisponible', 'Indisponible')], default='disponible', max_length=20),
        ),
    ]
