# Generated by Django 6.0.4 on 2026-07-26 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0002_produits_date_maj_produits_photo_produits_quantite_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produits',
            old_name='unite',
            new_name='unite_De_Mesure',
        ),
        migrations.RemoveField(
            model_name='produits',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='produits',
            name='quantite',
        ),
        migrations.RemoveField(
            model_name='produits',
            name='statut',
        ),
        migrations.AddField(
            model_name='produits',
            name='unitePrix',
            field=models.CharField(choices=[('US', 'Dollars'), ('HTG', 'Gourdes')], default='HTG', max_length=20),
        ),
        migrations.CreateModel(
            name='sousCategories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_categories', to='Produits.categories')),
            ],
            options={
                'verbose_name': 'sous categorie',
                'verbose_name_plural': 'sous categories',
                'db_table': 'sous_categories',
                'ordering': ['id'],
            },
        ),
    ]
