# Generated by Django 6.0.4 on 2026-07-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0003_rename_unite_produits_unite_de_mesure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='souscategories',
            name='nom',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
