# Generated by Django 6.0.4 on 2026-07-27 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0004_souscategories_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='produits',
            name='nombre_contacts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
