# Generated by Django 6.0.4 on 2026-07-29 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0005_produits_nombre_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='produits',
            name='sous_categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='Produits.souscategories'),
        ),
    ]
