# Generated by Django 6.0.4 on 2026-07-29 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0006_produits_sous_categorie'),
        ('Registration', '0015_profil_categories_produits'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactProduit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_contact', models.DateTimeField(auto_now_add=True)),
                ('acheteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_effectues', to='Registration.utilisateur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='Produits.produits')),
            ],
            options={
                'verbose_name': 'contact produit',
                'verbose_name_plural': 'contacts produits',
                'db_table': 'contacts_produits',
                'ordering': ['-date_contact'],
            },
        ),
    ]
