# Generated by Django 6.0.4 on 2026-08-01 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0007_contactproduit'),
        ('Registration', '0016_entreprise_departement_entreprise_section_communale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalementProduit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_probleme', models.CharField(choices=[('information_incorrecte', 'Informations incorrectes'), ('produit_obsolete', 'Produit obsolète / plus disponible'), ('contenu_inapproprie', 'Contenu inapproprié'), ('autre', 'Autre')], max_length=30)),
                ('motif', models.TextField()),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('admin_traitant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_traites', to='Registration.utilisateur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='Produits.produits')),
                ('signaleur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_effectues', to='Registration.utilisateur')),
            ],
            options={
                'verbose_name': 'signalement produit',
                'verbose_name_plural': 'signalements produits',
                'db_table': 'signalements_produits',
                'ordering': ['-date_signalement'],
            },
        ),
    ]
