# Generated by Django 6.0.4 on 2026-08-01 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0008_signalementproduit'),
        ('Registration', '0016_entreprise_departement_entreprise_section_communale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produits',
            name='nombre_avis',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produits',
            name='note_moyenne',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AvisProduit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('commentaire', models.TextField(blank=True)),
                ('date_avis', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avis_donnes', to='Registration.utilisateur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='Produits.produits')),
            ],
            options={
                'verbose_name': 'avis produit',
                'verbose_name_plural': 'avis produits',
                'db_table': 'avis_produits',
                'ordering': ['-date_avis'],
                'constraints': [models.UniqueConstraint(fields=('produit', 'auteur'), name='un_avis_par_utilisateur_et_produit')],
            },
        ),
    ]
