# Generated by Django 6.0.4 on 2026-08-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0009_produits_nombre_avis_produits_note_moyenne_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produits',
            name='desactive_par_signalements',
            field=models.BooleanField(default=False),
        ),
    ]
