# Generated by Django 6.0.4 on 2026-08-01 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0010_produits_desactive_par_signalements'),
        ('Registration', '0018_utilisateur_desactive_par_signalements'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalementVendeur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_probleme', models.CharField(choices=[('arnaque_fraude', 'Arnaque / fraude'), ('produits_non_conformes', 'Produits systématiquement non conformes'), ('comportement_inapproprie', 'Comportement inapproprié / harcèlement'), ('non_reponse', 'Ne répond jamais aux messages'), ('autre', 'Autre')], max_length=30)),
                ('motif', models.TextField()),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('admin_traitant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_vendeurs_traites', to='Registration.utilisateur')),
                ('signaleur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_vendeurs_effectues', to='Registration.utilisateur')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_vendeurs_recus', to='Registration.utilisateur')),
            ],
            options={
                'verbose_name': 'signalement vendeur',
                'verbose_name_plural': 'signalements vendeurs',
                'db_table': 'signalements_vendeurs',
                'ordering': ['-date_signalement'],
            },
        ),
    ]
