# Generated by Django 6.0.4 on 2026-08-01 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0011_signalementvendeur'),
        ('Registration', '0018_utilisateur_desactive_par_signalements'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalementAvis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_probleme', models.CharField(choices=[('contenu_inapproprie', 'Contenu inapproprié'), ('faux_avis', 'Faux avis / non authentique'), ('hors_sujet', 'Hors sujet'), ('autre', 'Autre')], max_length=30)),
                ('motif', models.TextField()),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('admin_traitant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_avis_traites', to='Registration.utilisateur')),
                ('avis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='Produits.avisproduit')),
                ('signaleur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_avis_effectues', to='Registration.utilisateur')),
            ],
            options={
                'verbose_name': 'signalement avis',
                'verbose_name_plural': 'signalements avis',
                'db_table': 'signalements_avis',
                'ordering': ['-date_signalement'],
            },
        ),
    ]
