# Generated by Django 6.0.4 on 2026-08-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0012_signalementavis'),
    ]

    operations = [
        migrations.AddField(
            model_name='produits',
            name='nombre_vues',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
