# Generated by Django 6.0.4 on 2026-08-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0013_produits_nombre_vues'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo_produits',
            options={'ordering': ['ordre', 'id']},
        ),
        migrations.AddField(
            model_name='photo_produits',
            name='ordre',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
