# Generated by Django 6.0.4 on 2026-08-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0014_alter_photo_produits_options_photo_produits_ordre'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalementproduit',
            name='resolu_automatiquement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signalementvendeur',
            name='resolu_automatiquement',
            field=models.BooleanField(default=False),
        ),
    ]
