# Generated by Django 6.0.4 on 2026-08-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Produits", "0015_signalementproduit_resolu_automatiquement_and_more"),
        ("Registration", "0027_backfill_super_super_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="signalementavis",
            name="historique_masque_pour",
            field=models.ManyToManyField(
                blank=True,
                related_name="signalements_avis_historique_masques",
                to="Registration.utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="signalementproduit",
            name="historique_masque_pour",
            field=models.ManyToManyField(
                blank=True,
                related_name="signalements_produits_historique_masques",
                to="Registration.utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="signalementvendeur",
            name="historique_masque_pour",
            field=models.ManyToManyField(
                blank=True,
                related_name="signalements_vendeurs_historique_masques",
                to="Registration.utilisateur",
            ),
        ),
    ]
