# Generated by Django 6.0.4 on 2026-08-09 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Produits", "0016_signalementavis_historique_masque_pour_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="signalementavis",
            name="auteur_avis_nom_snapshot",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="signalementavis",
            name="avis_commentaire_snapshot",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="signalementavis",
            name="avis_note_snapshot",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="signalementavis",
            name="explication_decision",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="signalementavis",
            name="produit_nom_snapshot",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="signalementproduit",
            name="explication_decision",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="signalementvendeur",
            name="explication_decision",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="signalementavis",
            name="avis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="signalements",
                to="Produits.avisproduit",
            ),
        ),
    ]
