# Generated by Django 6.0.4 on 2026-08-09 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Produits", "0017_signalementavis_auteur_avis_nom_snapshot_and_more"),
        ("Registration", "0028_vueprofilvendeur"),
    ]

    operations = [
        migrations.CreateModel(
            name="VueProduit",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date_vue", models.DateTimeField(auto_now_add=True)),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vues",
                        to="Produits.produits",
                    ),
                ),
                (
                    "visiteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vues_produits_effectuees",
                        to="Registration.utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "vue produit",
                "verbose_name_plural": "vues produits",
                "db_table": "vues_produits",
                "ordering": ["-date_vue"],
            },
        ),
    ]
