# Generated by Django 6.0.4 on 2026-08-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Produits", "0018_vueproduit"),
    ]

    operations = [
        migrations.AddField(
            model_name="categories",
            name="nom_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="nom (anglais)"
            ),
        ),
        migrations.AddField(
            model_name="categories",
            name="nom_ht",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="nom (kreyòl)"
            ),
        ),
        migrations.AddField(
            model_name="souscategories",
            name="nom_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="nom (anglais)"
            ),
        ),
        migrations.AddField(
            model_name="souscategories",
            name="nom_ht",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="nom (kreyòl)"
            ),
        ),
    ]
